In [128]:
# ДЗ к уроку 8
%matplotlib inline
import numpy as np
import matplotlib as mpl
import scipy.linalg
import scipy.optimize

In [122]:
# ДЗ 1
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
b = np.array([12, 2, 1])
d_a = np.linalg.det(A)
print("Determinant is:", d_a, "\n Let's find the only solusion")
x = np.dot(np.linalg.inv(A), b)
print("the result is vector:", x)
print("Check the result:", np.dot(A, x))

Determinant is: 59.999999999999986 
 Let's find the only solusion
the result is vector: [-9.2         0.9         6.46666667]
Check the result: [12.  2.  1.]


In [123]:
# ДЗ 2
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
b = np.array([1, 7, 12, 7, 15])
A_new = np.dot(np.transpose(A), A)
b_new = np.dot(np.transpose(A), b)
x = np.dot(np.linalg.inv(A_new), b_new)
print("Максимально приближеннное решение (псевдорешение):", x)
print("Проверка:", np.dot(A, x))


Максимально приближеннное решение (псевдорешение): [ 1.13919353 -0.90498444 -0.9009803 ]
Проверка: [ 0.23020495  7.03751834 11.83650981  6.78328855 15.21805313]


In [124]:
# ДЗ 3
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([12, 2, 1])
A_b = np.hstack((A, np.atleast_2d(b).T))
r_a = np.linalg.matrix_rank(A, 0.0001)
r_ab = np.linalg.matrix_rank(A_b, 0.0001)
print("Ранг матрицы системы:", r_a)
print("Ранг расширенной матрицы:", r_ab)
#определим совместна или нет ситстема. Далее произойдет выбор алгоритма решения
if r_a != r_ab:
    print("Ранги матрицы системы и основной матрицы не равны => система несовместна, точного решения нет")
    print("но можно найти псевдорешение по методу наименьших квадратов")
    A_new = np.dot(np.transpose(A), A)
    b_new = np.dot(np.transpose(A), b)
    x = np.dot(np.linalg.inv(A_new), b_new)
    print("Максимально приближеннное решение (псевдорешение):", x)
    print("Проверка:", np.dot(A, x))
else:
    x = np.dot(np.linalg.inv(A), b)
    print("the result is vector:", x)
    print("Check the result:", np.dot(A, x))

Ранг матрицы системы: 2
Ранг расширенной матрицы: 3
Ранги матрицы системы и основной матрицы не равны => система несовместна, точного решения нет
но можно найти псевдорешение по методу наименьших квадратов
Максимально приближеннное решение (псевдорешение): [-8.    0.    6.25]
Проверка: [10.75  5.5   0.25]


In [125]:
# ДЗ 4
# PLU-разложение
A = np.array([[1, 2, 3] , [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
# Проверкa LU-раздожения решения, которое на листочке
L= np.array([[1, 0, 0] , [2, 1, 0], [4, 20/12, 1]])
U= np.array([[1, 2, 3] , [0, 12, 15], [0, 0, 36]])
print(np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ 1.  2.  3.]
 [ 2. 16. 21.]
 [ 4. 28. 73.]]


In [129]:
#ДЗ 6
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([2, 5, 11])
A_b = np.hstack((A, np.atleast_2d(b).T))
r_a = np.linalg.matrix_rank(A, 0.0001)
r_ab = np.linalg.matrix_rank(A_b, 0.0001)
print("Ранг матрицы системы:", r_a)
print("Ранг расширенной матрицы:", r_ab)
#определим совместна или нет ситстема. Далее произойдет выбор алгоритма решения
if r_a != r_ab:
    print("Ранги матрицы системы и основной матрицы не равны => система несовместна, точного решения нет")
    print("но можно найти псевдорешение по методу наименьших квадратов")
    A_new = np.dot(np.transpose(A), A)
    b_new = np.dot(np.transpose(A), b)
    x = np.dot(np.linalg.inv(A_new), b_new)
    print("Максимально приближеннное решение (псевдорешение):", x)
    print("Проверка:", np.dot(A, x))
else:
    x = np.dot(np.linalg.inv(A), b)
    print("the result is vector:", x)
    print("Check the result:", np.dot(A, x))

Ранг матрицы системы: 2
Ранг расширенной матрицы: 3
Ранги матрицы системы и основной матрицы не равны => система несовместна, точного решения нет
но можно найти псевдорешение по методу наименьших квадратов
Максимально приближеннное решение (псевдорешение): [1. 0. 0.]
Проверка: [1. 4. 7.]
