In [22]:
%matplotlib inline
import numpy as np
import matplotlib as mpl

In [ ]:
#ДЗ 7.0. Проверка свойств сложения и умножения матриц
a = np.array([1, 2, 4],  [4, 0, 6], [7, 8, 9])
b = np.array([2, 3, 4], [2, 5, 8], [1, 3, 0])
k = 2
l = 3
print((k*l)*a)
print(k*(l*a))
print("")
print(k*(a +b))
print(k * a + k * b)
print("")
print((k + l) * a)
print(k * a + l * a)
print("")
print((a * b) * c)
print(a * (b * c))
print("")
print((a + b) * c)
print(a * c + b * c))
print("")
print((a * (b * c))
print(a * b + a * c))

In [52]:
# Урок7. ДЗ 5.1. Умножение векторов
v1 = np.array([5, 4, 6, 3, 9])
v2 = np.array([2, 1, 4, 5, 1])
print("Сложение")
print(np.add(v1, v2))
print("Вычитание")
print(np.subtract(v1, v2))
print("Транспонирование")
print(v1.transpose())
print(v2.transpose())
print("Обращение")
e = np.identity(5)
v_1 = v1 * e
print(np.linalg.inv(v_1))
print("Умножение")
print(v_1 * e)
k = 2
print(np.dot(v1, v2))
print(np.dot(v2, v1))
print(np.dot(k, v1))
print(k * (v1 + v2))
print(k * v1 * v2)

Сложение
[ 7  5 10  8 10]
Вычитание
[ 3  3  2 -2  8]
Транспонирование
[5 4 6 3 9]
[2 1 4 5 1]
Обращение
[[0.2        0.         0.         0.         0.        ]
 [0.         0.25       0.         0.         0.        ]
 [0.         0.         0.16666667 0.         0.        ]
 [0.         0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.11111111]]
Умножение
[[5. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 6. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 9.]]
62
62
[10  8 12  6 18]
[14 10 20 16 20]
[20  8 48 30 18]


In [57]:
# Урок7.Определители матриц
# ДЗ 5.2. Расчет определителя
matrix1 = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(matrix1)
det1 = 1 * (0*9 - 8*6)-2*(4*9-7*6)+3*(4*8-7*0)
print(det1)
print(np.linalg.det(matrix1))

[[1 2 3]
 [4 0 6]
 [7 8 9]]
60
59.999999999999986


In [66]:
# Урок7.Обратная матрица
# ДЗ 5.3. Расчет обращение матрицы
matrix2 = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(np.linalg.inv(matrix2))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [76]:
# ДЗ 5.3. Ранг матрицы
print(np.linalg.matrix_rank(matrix2, 0.0001))
matrix3 = np.array([[1, 2, 3, 4], [2, 4, 6, 8], [1, -2, -3, -4], [-2, -4, -6, -8]])
print(np.linalg.matrix_rank(matrix3, 0.0001))
print(np.linalg.matrix_rank(e, 0.0001))

3
1
3


In [79]:
#ДЗ 5.4.Скалярное произведение векторов
a = np.array([1, 5])
b = np.array([2, 8])
print(np.inner(a, b))

42


In [108]:
# ДЗ 5.5. Смешанное произведение векторов
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print(np.inner(v, c))
v = np.cross(b, c)
print(np.inner(a, v))

228.5
228.5
